spring.application.name=app

spring.datasource.url=jdbc:mysql://localhost:3306/appdb
spring.datasource.username=root
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update

# JWT Signature
jwt.key = udybsgbsdyb-shdvb
jwt.expiry = 86400000 
jwt.issuer = rahul

# AWS Credentials
aws.s3.access-key-id=AKIASIVGLKRWUB4K7HWW
aws.s3.secret-access-key=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
aws.s3.region=ap-south-1
aws.s3.bucket-name=myawsbucket821

#twilio
twilio.account.sid=AC5910e7536f46b01f70a73fe904de06b7
twilio.auth.token=94c11f0dc2899d00d21b92c9febf4f52
twilio.phone.number=+14177963079
